### ISSUE TITLE
It occurred ERROR when I make pev in Linux.

### ISSUE THREAD

**Issue by LakerMoon** [mentebinaria/readpe#171]
I installed openssl and libssl-dev, and i git clone new libpe.In libpe category, i make successfully.
But i came back pev/ and make it error:

Makefile:148: recipe for target 'build/./peres.o' failed
make[1]: *** [build/./peres.o] Error 1
make[1]: Leaving directory '/home/hy/code/pev-0.81/src'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by merces** [comment]
This error doesn't say much. =/ Did you clone the pev repo using the `--recursive` option as instructed [here](https://github.com/merces/pev#how-to-get-the-source-code)?

**Comment by dubrsl** [comment]
`peres.c:227:25: error: too few arguments to function 'pe_utils_str_widechar2ascii'
227 |                         pe_utils_str_widechar2ascii(ascii_string, (const char *)dataString->String, min_size);
|                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/pev-0.81/lib/libpe/include/libpe/utils.h:47:6: note: declared here
47 | void pe_utils_str_widechar2ascii(char *output, size_t output_size, const char *widechar, size_t widechar_count);
|      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:148: build/./peres.o] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/pev-0.81/src'`

**Comment by GoGoOtaku** [comment]
Looks like you tried to compile version 0.81 against a newer version of libpe.
Run `git submodule update` in the pev directory to check out the appropriate version. You might have to run `make clean` to clean out objects that were already compiled against the newer libpe.

**Comment by GoGoOtaku** [comment]
Since libpe is no longer a submodule I don't think this error will occur as easily anymore.
If this issue persist please reply again and we can reopen this issue.
