### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by notpeelz** [mentebinaria/readpe#209]
The version string wasn't bumped in the 0.83 release.
https://github.com/mentebinaria/readpe/blob/4a87bc9fac83a334dd2d6c4f63e9a5172b1d5fc7/include/common.h#L62
https://github.com/mentebinaria/readpe/blob/4a87bc9fac83a334dd2d6c4f63e9a5172b1d5fc7/lib/libpe/Makefile#L65
https://github.com/mentebinaria/readpe/blob/4a87bc9fac83a334dd2d6c4f63e9a5172b1d5fc7/pev.spec#L2
https://github.com/mentebinaria/readpe/blob/4a87bc9fac83a334dd2d6c4f63e9a5172b1d5fc7/doc/manual/en_us/pev.docbook#L46

**Comment by GoGoOtaku** [comment]
Thank you for noticing. I bumped and re-released the version. Since it was just a couple hours this should be fine.
